#!/bin/bash
cd /Users/larry/techlarry/wiki

set -e

echo "index.py: building contents pages..."
python index.py

echo "mkdocs build --clean"
echo "building .... "
mkdocs build --clean -q --site-dir=/Users/larry/techlarry.github.io/wiki/
#mkdocs build --dirty -q
echo "building complete!"
