#!/bin/bash
cd /Users/larry/note-os

source activate python27
set -e


echo "mkdocs build --dirty"
echo "building .... "
mkdocs build --dirty -q --site-dir=/Users/larry/techlarry.github.io/note-os/
echo "building complete!"
